name: .NET Tests & Auto-commit

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches-ignore: [main]
  workflow_dispatch:
  issue_comment:

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:

  check-target:
    runs-on: ubuntu-latest
    outputs:
      pr_valid: ${{ steps.check.outputs.pr_valid }}
    steps:
      - name: 🚫 Проверка PR в main
        id: check
        shell: bash
        run: |
          PR_BASE="${{ github.event.pull_request.base.ref || '' }}"
          echo "Base branch: $PR_BASE"
          if [ "$PR_BASE" = "main" ]; then
            echo "❌ Нельзя отправлять работу в main ветку."
            echo "pr_valid=false" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "✅ PR направлен в '$PR_BASE', можно запускать тесты."
            echo "pr_valid=true" >> $GITHUB_OUTPUT
          fi
  tests:
    name: Run test
    runs-on: windows-latest
    needs: check-target
    if: |
      (github.event_name == 'pull_request_target' && needs.check-target.outputs.pr_valid == 'true') ||
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'issue_comment'
    strategy:
      matrix:
        configuration: [Debug]

    steps:
    - name: Checkout code safely
      uses: actions/checkout@v4
      with:
        # Берем код из head PR только если это PR
        repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore
      run: dotnet restore Lab1/Lab1.sln

    - name: Build
      run: dotnet build Lab1/Lab1.sln --configuration ${{ matrix.configuration }} --no-restore

    - name: Run tests (Purple→Blue→Green→White)
      id: cascade
      shell: pwsh
      run: |
        $proj = 'Lab1test/Lab1test.csproj'
        $colors = @('Purple','Blue','Green','White')
        $listFile = 'tests-list.txt'

        Write-Host ">>> Generating tests list (this may still perform discovery)..."
        # Список всех тестов (без сборки, чтобы использовать уже собранные артефакты)
        dotnet test $proj --list-tests --no-build > $listFile 2>&1 || true

        Write-Host "=== tests-list.txt ==="
        Get-Content $listFile | ForEach-Object { Write-Host $_ }

        foreach ($c in $colors) {
          Write-Host "-------------------------------"
          Write-Host "🔎 Ищем тесты для класса: ${c}Test"
          # Берём первую строку из списка, которая содержит "<...>.<c>Test."
          $matchLine = Get-Content $listFile | Where-Object { $_ -match "\b${c}Test\." } | Select-Object -First 1

          if (-not $matchLine) {
            Write-Host "⚠️ Не найдено тестов для ${c}Test в списке. Пропускаем."
            continue
          }

          $fullTestName = $matchLine.Trim()
          Write-Host "Найденая тестовая строка: $fullTestName"

          # Разделим по точкам и уберём последний сегмент (имя метода)
          $parts = $fullTestName -split '\.'
          if ($parts.Length -lt 2) {
            Write-Host "⚠️ Непредвиденный формат строки: $fullTestName"
            continue
          }
          $classFqn = ($parts[0..($parts.Length - 2)]) -join '.'
          Write-Host "Полное имя класса: $classFqn"

          $filter = "FullyQualifiedName~$classFqn"
          Write-Host "Запускаем dotnet test с фильтром: $filter"

          dotnet test $proj `
            --no-build `
            --configuration $Env:CFG `
            --filter $filter `
            --logger "console;verbosity=detailed" `
            --logger "trx;LogFileName=test-$c.trx"

          if ($LASTEXITCODE -eq 0) {
            Write-Host "✅ Класс ${c}Test прошёл. Останавливаем каскад."
            exit 0
          } else {
            Write-Host "❌ Класс ${c}Test не прошёл — пробуем следующий."
          }
        }

        Write-Host "❌ НИ ОДИН класс не прошёл."
        exit 1
      env:
        CFG: ${{ matrix.configuration }}

    - name: Upload TRX
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: trx-${{ matrix.configuration }}
        path: '**/test-results.trx'
